apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
      - name: node-service
        image: docker.io/marcoliew/lgtm-node-service:v0.1.0 # <-- UPDATE YOUR HUB USERNAME/TAG
        ports:
        - containerPort: 8080
        env:
        # Crucial for OTel SDK: Points to the Collector Service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.monitoring.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "node-lgtm-service"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer # Expose the Node service publicly for triggering traffic