apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-demo-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcolw/lgtm_engineer_challenge.git # <-- UPDATE YOUR USERNAME/REPO
    targetRevision: HEAD
    path: k8s/demo-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Deploy the apps into the 'default' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true