apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-logs-traces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.28.1 # Use a recent, stable version
    chart: tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# We install Loki separately
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.11.0 # Use a recent, stable version
    chart: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true