apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/marcolw/lgtm_engineer_challenge.git
    targetRevision: HEAD
    path: k8s/observability # Points to the folder containing the App manifests below
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # The App definitions live in argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true